dist: xenial
services:
    - mongodb
language: python
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.7"
      env: TOXENV=py37-qa
install:
    - pip install tox-travis coveralls
script: tox
after_success:
    - coveralls
notifications:
  email: false
